require("plugins.autoclose")
require("plugins.catppuccin")
require("plugins.feline")
require("plugins.gitsigns")
require("plugins.image")
require("plugins.indent-blankline")
require("plugins.nvim-lspconfig")
require("plugins.nvim-tree")
require("plugins.nvim-treesitter")
require("plugins.prettier")
require("plugins.telescope")
-- require("plugins.terminal")
require("plugins.tint")

